{% set name = "galpy" %}
{% set version = "1.6.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 721d3fa5b156a02a4d9e9ae58a29f946c716ff40a2bd6e4a6f8c06bdfe8f7c57

build:
  number: 0
  skip: true  # [win and vc<14]
  script:
    - rm gsl-config.bat  # [win and py2k]
    - python setup.py install --single-version-externally-managed --record=record.txt  # [win and py2k]
  script: python setup.py install --single-version-externally-managed --record=record.txt --no-openmp  # [win and py3k]
  script: CPATH="$PREFIX/include:$CPATH" python setup.py install --single-version-externally-managed --record=record.txt --no-openmp  # [osx]
  script: CPATH="$PREFIX/include:$CPATH" python setup.py install --single-version-externally-managed --record=record.txt  # [not win and not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib-base
    - six
    - future
    - gsl
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - six
    - future
    - gsl

test:
  imports:
    - galpy

about:
  home: http://github.com/jobovy/galpy
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Galactic Dynamics in python
  description: |
    galpy is a Python 2 and 3 package for galactic dynamics. It supports orbit
    integration in a variety of potentials, evaluating and sampling various
    distribution functions, and the calculation of action-angle coordinates
    for all static potentials. galpy is an astropy affiliated package and
    provides full support for astropy’s Quantity framework for variables with
    units.
  doc_url: http://galpy.readthedocs.io/en/latest/
  dev_url: http://github.com/jobovy/galpy

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - jobovy
