appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Z+sF1FXvJ6bpTh75AF9bFJ4H4v4Y8JAsak4oL0w2yh8nnzmHVG770Zky1CQdlIP6n9jMRiSOveboKPo6IVfOdv6Oyk+JP3prTELF15L0d93Gd8csQUCdSCj21XjyYDqL8Gxty6sEJ1waLLbZ6AnVi5sh9B4kDiQytqFdOePFAXATICnDOtKnOdq6RzqJSTSrtuWiDZ/R08DjyySr1XYMuTI1APQHvZiCZ9REnGCBn2P/DvRQyIIEOTWp8v4l1MaIpp1GcVsQ+WTctIz5NVefR+B1JoNwra6jzrDnOrPZrL+sJovpqif5cPUmzhNeGuDGkI7DI5qy27aso8plVzZLGqteT0ekfepvTo+uh8+7MMmDFeXyeSPZA27nK/O7+YmaKy78WJjagMHTp/uvq+JJ9SVRgLoc6eWyZGVwPkYkPd1htGQIr/5+Ak7ETanUF4nXf+OnNzk5JSKlW8yBV9rEnheX9Gw2mcp5HxjFMFV6JOaHC/8TBC4yzf6jchu855TXxaX5wgtlVyqTWdizFSR7MBj+DuHlzlZU+r1TAX/bnJDj7X/P1I8yQHIxQ//Pz3BdbxDA2oPFuiu2XX8s41ToZqm6RoEnbCWFI5VLTq5Xm9uHNDG/NsCDgLqP9Jf8+A8L4E22QNeLm9dtPRS2568/xY56g4XupFrz5tvf5WtEtJg=}
provider:
  win: azure
